# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

    config.vm.box = "CentOS-6.4-x86_64-v20130427.box"
    config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box"

    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--acpi", "on"]
        vb.customize ["modifyvm", :id, "--chipset", "ich9" ]
        # vb.customize ["modifyvm", :id, "--cpus", "2" ]
        vb.customize ["modifyvm", :id, "--hwvirtex", "on" ]
        vb.customize ["modifyvm", :id, "--hwvirtexexcl", "on" ]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        
        # Enabling DNS proxy in NAT mode
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        # Using the host's resolver as a DNS proxy in NAT mode
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--nestedpaging", "on" ]
        vb.customize ["modifyvm", :id, "--rtcuseutc", "off" ]
        vb.customize ["modifyvm", :id, "--usb", "off" ]
        vb.customize ["modifyvm", :id, "--usbehci", "off" ]
        vb.customize ["modifyvm", :id, "--vtxvpid", "on" ]

        # nmi_watchdog=0
        #v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    end

    #On mac setup port forwarding.
    # sudo ipfw add 100 fwd 127.0.0.1,8080 tcp from any to any 80 in
    # sudo ipfw add 100 fwd 127.0.0.1,8443 tcp from any to any 443 in


    #default http
    #config.vm.network :forwarded_port, guest: 80, host: 8080

    # used for Node server
    #config.vm.network :forwarded_port, guest: 8124, host: 8124
    # config.vm.network :forwarded_port, guest: 443, host: 443
    #config.vm.network :forwarded_port, guest: 443, host: 8443
    
    #redis
    #config.vm.network :forwarded_port, guest: 6379, host: 6379
    
    #redis control
    #config.vm.network :forwarded_port, guest: 9001, host: 9001
    
    #Supervisord
    #config.vm.network :forwarded_port, guest: 9002, host: 9002

    # config.vm.network :private_network, ip: "192.168.57.57"
    config.vm.hostname = "vagrant.basereality.test"

 
  # Downloads too much data.
  # config.vm.provision :shell, :inline => "yum update"
  #  config.vm.provision :shell, :path => "../../scripts/bootstrap.sh"

  config.vm.synced_folder "/documents/projects/github", "/home/github/", :extra => 'dmode=777,fmode=777'
  config.vm.synced_folder "/temp", "/temp"
  config.vm.provision :shell, :path => "../scripts/bootstrapVagrant.sh", :args => "1"

end



