package "autoconf"
package "bison"
package "re2c"
package "bzip2-devel"
package "libcurl-devel"
package "libjpeg-turbo-devel"
package "libpng-devel"
package "libxml2-devel"
package "freetype-devel"
package "libpng"
package "libjpeg-turbo"
package "libmcrypt-devel"
package "libicu-devel"
package "libyaml-devel"
package "git"
package "ghostscript"
package "gcc"
package "gcc-c++"
package "openssl-devel"
package "siege"
package "strace"
package "fftw"
package "fftw-devel"
package "rpm-build"
package "pcre-devel"
package "createrepo"
package "libyaml-devel"

package "jasper-devel"
package "lcms-devel"
package "libX11-devel"
package "libXext-devel"
package "libXt-devel"
package "ghostscript-devel"
package "libtiff-devel"
package "libwebp-devel"
package "giflib-devel"
package "libtool"

package "valgrind"
package "composer-2015_02_28"


#Sphinx packages
#package "babel"
#package "setuptools"
#package "elementtree"
#package "meld3"
#package "Sphinx"
#package "snowballstemmer"
#package "docutils"
#package "Pygments"
#package "Jinja2"
#package "six"
#package "pytz"
#package "MarkupSafe"



