package "autoconf"
package "bison"
package "re2c"
package "bzip2-devel"
package "libcurl-devel"
package "libjpeg-turbo-devel"
package "libpng-devel"
package "libxml2-devel"
package "freetype-devel"
package "libpng"
package "libjpeg-turbo"
package "libmcrypt-devel"
package "libicu-devel"
package "libyaml-devel"
package "git"
package "ghostscript"
package "gcc"
package "gcc-c++"
package "openssl-devel"
package "siege"
package "strace"
package "fftw"
package "fftw-devel"
package "rpm-build"
package "pcre-devel"
package "createrepo"
package "libyaml-devel"

#package "ImageMagick-devel"

#package "libgearman"
#package "libgearman-devel"
#package "redis"
#package "java-1.6.0-openjdk"
#package "phpcustom"
#package "imagick"

#Sphinx packages
#package "babel"
#package "setuptools"
#package "elementtree"
#package "meld3"
#package "Sphinx"
#package "snowballstemmer"
#package "docutils"
#package "Pygments"
#package "Jinja2"
#package "six"
#package "pytz"
#package "MarkupSafe"



